source:
  source_file: tawantesxt1.txt
  input_path: E:\PyProj\TD_TT\Q2\source
  output_path: E:\PyProj\TD_TT\Q2\output

transform:
  - lowercase
  - whitespace
  - tab
  - ascii
  - email

stat_type:
  - alphabet_count
  - most_used_alphabet
